---
# tasks file for baseline_packages-ansible-role

- name: Set packages variable to defaults if not supplied by user
  set_fact:
    packages: {{ __packages | list }}
  when: packages is not defined

- name: Install all packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ packages }}"